"""
Bitsy Parts - Body parts and character components.

Provides drawable parts for character assembly including
heads, bodies, hair, eyes, and accessories.
"""

from .base import (
    Part,
    PartConfig,
)

from .heads import (
    Head,
    RoundHead,
    OvalHead,
    SquareHead,
    ChibiHead,
    TriangleHead,
    HeartHead,
    create_head,
    list_head_types,
    HEAD_TYPES,
)

from .bodies import (
    Body,
    BodyType,
    ChibiBody,
    SimpleBody,
    MuscularBody,
    SlimBody,
    Limb,
    ChibiArm,
    SimpleArm,
    ChibiLeg,
    SimpleLeg,
    Hand,
    Foot,
    create_body,
    create_limb,
    list_body_types,
    list_limb_types,
    get_body_proportions,
    BODY_TYPES,
    LIMB_TYPES,
)

from .hair import (
    Hair,
    FluffyHair,
    SpikyHair,
    LongHair,
    ShortHair,
    BaldHead,
    PonytailHair,
    TwinTailsHair,
    create_hair,
    list_hair_types,
    HAIR_TYPES,
)

from .eyes import (
    Eyes,
    EyeColors,
    SimpleEyes,
    RoundEyes,
    LargeEyes,
    SparkleEyes,
    ClosedEyes,
    AngryEyes,
    SadEyes,
    create_eyes,
    list_eye_types,
    get_eye_colors,
    blue_eyes,
    green_eyes,
    brown_eyes,
    purple_eyes,
    red_eyes,
    gold_eyes,
    EYE_TYPES,
    EYE_COLOR_PRESETS,
)

from .equipment import (
    EquipmentSlot,
    DrawLayer,
    AttachmentPoint,
    EquipmentConfig,
    Equipment,
)

from .armor import (
    Helmet,
    SimpleHelmet,
    KnightHelmet,
    WizardHat,
    Crown,
    Hood,
    ChestArmor,
    Breastplate,
    ChainMail,
    Robe,
    LeatherArmor,
    LegArmor,
    Greaves,
    Pants,
    Boots,
    PlateBoots,
    LeatherBoots,
    Sandals,
)

from .weapons import (
    Weapon,
    Sword,
    Longsword,
    Dagger,
    Staff,
    MagicStaff,
    Wand,
    Bow,
    Crossbow,
    Axe,
    DoubleAxe,
    Hammer,
    Spear,
)

from .accessories import (
    Cape,
    SimpleCape,
    RoyalCape,
    TatteredCape,
    Shield,
    RoundShield,
    KiteShield,
    TowerShield,
    BucklerShield,
    Belt,
    SimpleBelt,
    UtilityBelt,
    Wings,
    Scarf,
    Backpack,
)

__all__ = [
    # Base
    'Part',
    'PartConfig',

    # Heads
    'Head',
    'RoundHead',
    'OvalHead',
    'SquareHead',
    'ChibiHead',
    'TriangleHead',
    'HeartHead',
    'create_head',
    'list_head_types',
    'HEAD_TYPES',

    # Bodies
    'Body',
    'BodyType',
    'ChibiBody',
    'SimpleBody',
    'MuscularBody',
    'SlimBody',
    'Limb',
    'ChibiArm',
    'SimpleArm',
    'ChibiLeg',
    'SimpleLeg',
    'Hand',
    'Foot',
    'create_body',
    'create_limb',
    'list_body_types',
    'list_limb_types',
    'get_body_proportions',
    'BODY_TYPES',
    'LIMB_TYPES',

    # Hair
    'Hair',
    'FluffyHair',
    'SpikyHair',
    'LongHair',
    'ShortHair',
    'BaldHead',
    'PonytailHair',
    'TwinTailsHair',
    'create_hair',
    'list_hair_types',
    'HAIR_TYPES',

    # Eyes
    'Eyes',
    'EyeColors',
    'SimpleEyes',
    'RoundEyes',
    'LargeEyes',
    'SparkleEyes',
    'ClosedEyes',
    'AngryEyes',
    'SadEyes',
    'create_eyes',
    'list_eye_types',
    'get_eye_colors',
    'blue_eyes',
    'green_eyes',
    'brown_eyes',
    'purple_eyes',
    'red_eyes',
    'gold_eyes',
    'EYE_TYPES',
    'EYE_COLOR_PRESETS',

    # Equipment
    'EquipmentSlot',
    'DrawLayer',
    'AttachmentPoint',
    'EquipmentConfig',
    'Equipment',

    # Armor
    'Helmet',
    'SimpleHelmet',
    'KnightHelmet',
    'WizardHat',
    'Crown',
    'Hood',
    'ChestArmor',
    'Breastplate',
    'ChainMail',
    'Robe',
    'LeatherArmor',
    'LegArmor',
    'Greaves',
    'Pants',
    'Boots',
    'PlateBoots',
    'LeatherBoots',
    'Sandals',

    # Weapons
    'Weapon',
    'Sword',
    'Longsword',
    'Dagger',
    'Staff',
    'MagicStaff',
    'Wand',
    'Bow',
    'Crossbow',
    'Axe',
    'DoubleAxe',
    'Hammer',
    'Spear',

    # Accessories
    'Cape',
    'SimpleCape',
    'RoyalCape',
    'TatteredCape',
    'Shield',
    'RoundShield',
    'KiteShield',
    'TowerShield',
    'BucklerShield',
    'Belt',
    'SimpleBelt',
    'UtilityBelt',
    'Wings',
    'Scarf',
    'Backpack',
]
